name: Build App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Ionic
        uses: coturiv/setup-ionic@v1.0.3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build
        run: |
          ./ToolChains/bin/build all -pf android --build
          ls -l App/platforms/android/app/build/outputs/apk/debug